# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

# Project
mod_version=2.0.1
maven_group=net.anvian.simplemango
archives_name=simplemango
enabled_platforms=fabric,forge

# Minecraft
minecraft_version=1.19.4
minecraft_versions=1.19.4

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.87.2+1.19.4

# Forge
forge_version=1.19.4-45.4.5

# Anvian's Lib
anvianslib_version=1.4
